[package]
name = "sensor-transport"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
sensor-protocol = { path = "../sensor-protocol" }
thiserror.workspace = true
sensor-core = { path = "../sensor-core" }
sensor-identity = { path = "../sensor-identity" }
sensor-session = { path = "../sensor-session" }
sensor-crypto = { path = "../sensor-crypto" }
serde.workspace = true

[dev-dependencies]
serde.workspace = true
